---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: formation-lap
  labels:
    app: ott-users
    managed-by: argocd
spec:
  type: ClusterIP
  selector:
    app: ott-users
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
