apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

images:
  - name: 570795932693.dkr.ecr.ap-northeast-2.amazonaws.com/user-service
    newTag: latest
  - name: 570795932693.dkr.ecr.ap-northeast-2.amazonaws.com/backend-api
    newTag: latest

