apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  # 계정 ID 관련 오버라이드 파일들
  - backend-api/serviceaccount.yaml
  - backend-api/configmap.yaml

images:
  - name: 570795932693.dkr.ecr.ap-northeast-2.amazonaws.com/user-service
    newTag: latest
  - name: 570795932693.dkr.ecr.ap-northeast-2.amazonaws.com/backend-api
    newTag: latest

