apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

images:
  - name: 404457776061.dkr.ecr.ap-northeast-2.amazonaws.com/y2om-user-service
    newTag: v4

  - name: 404457776061.dkr.ecr.ap-northeast-2.amazonaws.com/ott-content
    newTag: v4

