---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: formation-lap
type: Opaque
stringData:
  KEYCLOAK_CLIENT_SECRET: ""
  KEYCLOAK_ADMIN_USERNAME: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  MEILISEARCH_API_KEY: "masterKey1234567890"
  DATABASE_URL: "<DATABASE_URL>"  # RDS Proxy ¿£µåÆ÷ÀÎÆ® »ç¿ë (Terraform¿¡¼­ »ý¼ºµÈ °ª)
