apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: formation-lap

resources:
  - namespace.yaml
  - configmap/db-config.yaml
  - configmap/keycloak-config.yaml
  - secret/db-secret.yaml
  - secret/keycloak-secret.yaml
  - ingress.yaml
  - backend-api
  - user-service
# Force ArgoCD refresh
