apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap/db-config.yaml
  - secret/db-secret.yaml
  - deployment/user-deployment.yaml
  - services/user-service.yaml
  - ingress.yaml
  - backend-api

