---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: formation-lap
data:
  APP_NAME: "Backend API"
  APP_VERSION: "1.0.0"
  DEBUG: "false"
  ENVIRONMENT: "production"
  HOST: "0.0.0.0"
  PORT: "8000"
  ROOT_PATH: "/api"
  KEYCLOAK_URL: "https://api.matchacake.click/keycloak"
  KEYCLOAK_REALM: "formation-lap"
  KEYCLOAK_CLIENT_ID: "backend-client"
  JWT_ALGORITHM: "RS256"
  MEILISEARCH_URL: "http://meilisearch-service:7700"
  DB_PORT: "3306"
  DB_NAME: "ott_db"
  S3_BUCKET_NAME: "yuh-team-formation-lap-origin-s3-404457776061"
  S3_REGION: "ap-northeast-2"
  CLOUDFRONT_DOMAIN: "www.matchacake.click"
