apiVersion: apps/v1
kind: Deployment
metadata:
  name: ott-users
  namespace: formation-lap
  labels:
    app: ott-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ott-users
  template:
    metadata:
      labels:
        app: ott-users
    spec:
      containers:
        - name: ott-users
          image: 404457776061.dkr.ecr.ap-northeast-2.amazonaws.com/y2om-user-service
          command: ["uvicorn"]
          args: ["main:app", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - containerPort: 8000

