apiVersion: apps/v1
kind: Deployment
metadata:
  name: ott-users
spec:
  template:
    spec:
      containers:
      - name: ott-users
        image: 404457776061.dkr.ecr.ap-northeast-2.amazonaws.com/y2om-user-service
        command: ["uvicorn"]
        args: ["main:app", "--host", "0.0.0.0", "--port", "8000"]

